def name_1():
    print("ugo tskhadadze")
name_1()

def name_2():
    print("giorgi bibilashvili")
name_2() 



def name_3():
    print("raul tskhadadze")
name_3()



def name_4():
    print("nana glurjidze ")
name_4()





def name_5():
    print("liza tskhadadze")
name_5()



def name_6():
    print("luka chubinidze")
name_6()




def name_7():
    print("denis tskhadadze")
name_7()



def name_8():
    print("tamar iveri")
name_8()




def name_9():
    print("tamar glurjidze")
name_9()



def name_10():
    print("mia tskhadadze")
name_10()